module.exports = {
	arrowParens: "always",
	bracketSameLine: true,
	bracketSpacing: true,
	embeddedLanguageFormatting: "auto",
	endOfLine: "lf",
	experimentalTernaries: true,
	experimentalOperatorPosition: "start",
	htmlWhitespaceSensitivity: "strict",
	insertPragma: false,
	jsxSingleQuote: false,
	jsxBracketSameLine: true,
	printWidth: 80,
	proseWrap: "always",
	quoteProps: "consistent",
	requirePragma: false,
	semi: true,
	singleAttributePerLine: true,
	singleQuote: false,
	tabWidth: 2,
	trailingComma: "all",
	useTabs: true,
	vueIndentScriptAndStyle: true,
	rangeStart: 0,
	rangeEnd: Infinity,
	//parser: <string>, // Padrão: <string>
	//filepath: <string>, // Padrão: <string>
	plugins: ["prettier-plugin-tailwindcss"],
};
